### ISSUE TITLE
update carrier verison to latest

### ISSUE THREAD

**Issue by liyangwood** [cyber-republic/elastos-unity-carrier#30]

**Comment by jmsaulnier** [comment]
@liyangwood core team released CocaoPods iOS lib for Carrier you should use it 🙌 (and they are planning to release on Maven - so it will be easy to import on Android)

**Comment by jmsaulnier** [comment]
@liyangwood https://mvnrepository.com/artifact/org.elastos/carrier/5.2.2 so looks like you can use now Gradle ``` compile group: 'org.elastos', name: 'carrier', version: '5.2.2' ``` to add Elastos Android SDK

**Comment by ademcan** [comment]
I will try to keep an eye on the different releases of the Carrier (and Wallet) SDKs and update them accordingly in the different Elastos Unity repositories. I am closing this issue for the sake of completeness. Thank you!
